version: '3.8'

services:
  # Next.js application
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/taskmanagement
      - NEXTAUTH_SECRET=your_nextauth_secret
      - NEXTAUTH_URL=http://localhost:3000

  # MongoDB database
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=taskmanagement

volumes:
  mongodb-data: